version: '4.6'

services:
  # O Banco de Dados
  db:
    image: postgres:15
    container_name: asset_manager_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Ferramenta visual para ver o banco (tipo um Excel para SQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: asset_manager_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: